apiVersion: v1
kind: Service
metadata:
  name: wstore-frontend
spec:
  type: LoadBalancer
  selector:
    app: wstore-front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  externalTrafficPolicy: Local
---
apiVersion: v1
kind: Service
metadata:
  name: wstore-backend
spec:
  type: NodePort
  selector:
    app: wstore-back
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wstore-front
spec:
  serviceName: "wstore-frontend"
  replicas: 1
  selector:
    matchLabels:
      app: wstore-front
  template:
    metadata:
      labels:
        app: wstore-front
    spec:
      containers:
      - name: wstore
        image: iad.ocir.io/axfo51x8x2ap/devlive-winestore:latest
        command: ["java", "-jar", "./wineStore.jar"]
        ports:
        - containerPort: 8080
        env:
          - name: spring.config.location
            value: file:/spring/wstore.properties
          - name: spring.web.resources.static-locations
            value: file:/spring/static/
          - name: winStore.services.adservice
            value: http://${WSTORE_BACKEND_SERVICE_HOST}:${WSTORE_BACKEND_SERVICE_PORT}/adService/prodId
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wstore-back
spec:
  serviceName: "wstore-backend"
  replicas: 2
  selector:
    matchLabels:
      app: wstore-back
  template:
    metadata:
      labels:
        app: wstore-back
    spec:
      containers:
      - name: wstore
        image: iad.ocir.io/axfo51x8x2ap/devlive-winestore:latest
        command: ["java", "-jar", "./wineStore.jar"]
        ports:
        - containerPort: 8080
        env:
          - name: spring.config.location
            value: file:/spring/wstore.properties
          - name: spring.web.resources.static-locations
            value: file:/spring/static/
          - name: wineStore.db.url
            value: jdbc:mysql://<mds-private-ip-address>/wine
          - name: wineStore.db.password
            value: O&Mdemo1
